"""Regenerate and check source-of-truth artifacts consumed outside Python."""

from __future__ import annotations

import os
import sys
import argparse

import mujoco

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)

import kuafu_physics as P


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = os.path.join(ROOT, "stm32_firmware", "Core", "Inc", "kuafu_generated.h")
    expected = "#ifndef KUAFU_GENERATED_H\n#define KUAFU_GENERATED_H\n\n"
    expected += "/* AUTO-GENERATED from kuafu_physics.py. Regenerate with rl/verify/generate_artifacts.py. */\n"
    expected += P.codegen_firmware_header().replace(
        "/* AUTO-GENERATED by kuafu_physics.codegen_firmware_header — 禁止手改 */\n", "")
    expected += "\n\n#endif\n"
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as current:
            actual = current.read()
    else:
        actual = None
    if actual != expected and not args.check:
        temporary = f"{path}.tmp"
        with open(temporary, "w", encoding="utf-8") as output:
            output.write(expected)
        os.replace(temporary, path)
        actual = expected
        print(f"generated artifact written: {path}")
    if actual != expected:
        print(f"generated artifact differs: {path}")
        return 1
    xml_path = os.path.join(ROOT, "rl", "kuafu.xml")
    model = mujoco.MjModel.from_xml_path(xml_path)
    wheel = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, "wheel_l_geom")
    hip_a = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "hip_A_l")
    hip_b = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "hip_B_l")
    checks = [
        (abs(model.opt.timestep - P.PHYS_DT) < 1e-9, "physics timestep"),
        (abs(model.geom_size[wheel, 0] - P.R) < 1e-9, "wheel radius"),
        (model.geom_type[wheel] == mujoco.mjtGeom.mjGEOM_CAPSULE, "MJX-compatible wheel collision"),
        (abs(model.jnt_range[hip_a, 0] + 3.3) < 1e-9 and abs(model.jnt_range[hip_a, 1] - 3.3) < 1e-9, "hip A range"),
        (abs(model.jnt_range[hip_b, 0] + 3.3) < 1e-9 and abs(model.jnt_range[hip_b, 1] - 3.3) < 1e-9, "hip B range"),
    ]
    invalid = [name for ok, name in checks if not ok]
    if invalid:
        print("XML diverges from physics source: " + ", ".join(invalid))
        return 1
    print(f"generated artifact matches: {path}")
    print("XML source checks: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
