"""Evaluate frozen scenario summaries against KUAFU simulation release gates.

The scenario runner writes one JSON record per frozen bucket.  This verifier keeps
the gate decision deterministic and makes confidence-bound requirements explicit.
"""

from __future__ import annotations

import argparse
import json
import math


def wilson_lower_bound(successes: int, trials: int, z: float = 1.959963984540054) -> float:
    if trials <= 0 or not 0 <= successes <= trials:
        raise ValueError("invalid binomial result")
    p = successes / trials
    denom = 1.0 + z * z / trials
    centre = p + z * z / (2.0 * trials)
    radius = z * math.sqrt((p * (1.0 - p) + z * z / (4.0 * trials)) / trials)
    return (centre - radius) / denom


def validate(summary: dict) -> list[str]:
    failures: list[str] = []
    s0 = summary.get("s0")
    if s0 is None or not all(key in s0 for key in ("survival_rate", "tilt_rms_deg", "saturation_failures")) or \
       not all(math.isfinite(float(s0[key])) for key in ("survival_rate", "tilt_rms_deg")) or \
       s0["survival_rate"] < 0.99 or s0["tilt_rms_deg"] > 2.0 or s0["saturation_failures"] != 0:
        failures.append("S0 survival/orientation/saturation")
    buckets = summary.get("command_buckets")
    if not isinstance(buckets, list) or not buckets:
        failures.append("missing command_buckets")
    else:
        for bucket in buckets:
            if not all(key in bucket for key in ("name", "velocity_mae", "yaw_mae")):
                failures.append("command bucket missing required fields")
                continue
            if not all(math.isfinite(float(bucket[key])) for key in ("velocity_mae", "yaw_mae")):
                failures.append(f"{bucket.get('name', 'unknown')}: non-finite command metric")
                continue
            if bucket["velocity_mae"] > 0.10:
                failures.append(f"{bucket['name']}: velocity MAE")
            if bucket["yaw_mae"] > 0.15:
                failures.append(f"{bucket['name']}: yaw MAE")
    d0 = summary.get("d0_roll")
    if d0 is None or not all(key in d0 for key in ("d0_mae_mm", "roll_rms_deg", "settle_s")) or \
       not all(math.isfinite(float(d0[key])) for key in ("d0_mae_mm", "roll_rms_deg", "settle_s")) or \
       d0["d0_mae_mm"] > 5.0 or d0["roll_rms_deg"] > 2.0 or d0["settle_s"] > 0.5:
        failures.append("S2 D0/roll")
    slopes = summary.get("slopes")
    if not isinstance(slopes, list) or not slopes:
        failures.append("missing slopes")
    for slope in slopes or []:
        if not all(key in slope for key in ("name", "success_rate")) or not math.isfinite(float(slope.get("success_rate", float("nan")))):
            failures.append("invalid slope result")
            continue
        if slope["success_rate"] < 0.90:
            failures.append(f"{slope['name']}: slope success")
    stair = summary.get("stair_30mm")
    if stair is None or not all(key in stair for key in ("successes", "trials", "max_recovery_s")) or \
       not isinstance(stair["successes"], int) or not isinstance(stair["trials"], int) or \
       stair["trials"] <= 0 or not math.isfinite(float(stair["max_recovery_s"])) or \
       stair["max_recovery_s"] > 2.0 or wilson_lower_bound(stair["successes"], stair["trials"]) < 0.80:
        failures.append("S5 30mm stair Wilson lower bound")
    push = summary.get("push")
    if push is None or not all(key in push for key in ("recover_rate", "max_recovery_s", "baseline_recover_rate")) or \
       not all(math.isfinite(float(push[key])) for key in ("recover_rate", "max_recovery_s", "baseline_recover_rate")) or \
       push["recover_rate"] < 0.90 or push["max_recovery_s"] > 2.0 or \
       push["recover_rate"] <= push["baseline_recover_rate"]:
        failures.append("S6 push recovery")
    s3 = summary.get("s3")
    if s3 is None or "max_degradation" not in s3 or not math.isfinite(float(s3["max_degradation"])) or s3["max_degradation"] > 0.10:
        failures.append("S3 DR degradation")
    s7 = summary.get("s7")
    if s7 is None or s7.get("passed") is not True:
        failures.append("S7 mixed holdout")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate KUAFU frozen release summary")
    parser.add_argument("summary", help="JSON generated by frozen scenario evaluation")
    args = parser.parse_args()
    with open(args.summary, encoding="utf-8") as source:
        summary = json.load(source)
    failures = validate(summary)
    if failures:
        print("release gate failed:")
        for failure in failures:
            print(f"  - {failure}")
        return 1
    print("release gate passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
